### ISSUE TITLE
error while uploading file

### ISSUE THREAD

**Issue by 1746705990** [robinkarlberg/transfer.zip-web#10]
Hello, I am a novice. I deployed the project on the server, but when I uploaded the file, I reported an error.
![image](https://github.com/robinkarlberg/transfer.zip-web/assets/126673150/26cb8ba7-dd44-412d-aaf0-3b817bd0676e)
![image](https://github.com/robinkarlberg/transfer.zip-web/assets/126673150/2d4ed1ee-cc33-4891-9a0d-a38f8eb8185f)
There doesn't seem to be anything obviously wrong on the server's terminal, hope I can get your help.

**Comment by chouxiang99** [comment]
+1

**Comment by mathiasmagnusson** [comment]
[crypto.randomUUID](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) is only available in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts), which basically means either on localhost or on a website using https.

While `randomUUID` _could_ be replaced with something less secure, such as `Math.random`, that _could_ perhaps be problematic.

I believe that the best solution is to get yourself a tls (https) certificate (from e.g. letsencrypt).

**Comment by 1746705990** [comment]
@mathiasmagnusson 
Excuse me, thank you very much for your previous reply, this time I added the certificate. But a new error appeared.
![image](https://github.com/robinkarlberg/transfer.zip-web/assets/126673150/ceb4b28d-3585-4608-abb5-5748f6671cd1)
![image](https://github.com/robinkarlberg/transfer.zip-web/assets/126673150/124aab12-117c-4bb0-8f33-d7851d3c24d4)

**Comment by mathiasmagnusson** [comment]
I'm guessing you have a reverse proxy in front of the container? In that case it has to be configured to be able to proxy web socket connections as that is usually not supported by default.

**Comment by 1746705990** [comment]
Thanks for your reply, I'll try again.

**Comment by EmPiFree** [comment]
> I'm guessing you have a reverse proxy in front of the container? In that case it has to be configured to be able to proxy web socket connections as that is usually not supported by default.

Can you help with that?
I have a reverse proxy configured with apache2.

So that "https://transfer.my.domain.com" points at https://127.0.0.1:9001 and the transfer gui is showing up.
But how do I configure to get the WebSocket work?

I get the error:
`WebSocket connection to 'wss://transfer.my.domain.com/ws' failed`

**Comment by mathiasmagnusson** [comment]
Try googling "apache2 proxy websocket"
