### ISSUE TITLE
How should transferzip support HTTP

### ISSUE THREAD

**Issue by hausen1012** [robinkarlberg/transfer.zip-web#14]
How should transferzip support HTTP

**Comment by robinkarlberg** [comment]
That is not possible, because the built-in crypto API used by the browser is blocked on HTTP

**Comment by robinkarlberg** [comment]
I googled around a little and seems like the Service Worker won't work for self-signed certs. There seem to be some ways around it by changing browser settings, but you'd have to do that for every browser and device you want to use. I believe you need a valid certificate or run it on localhost.

**Comment by hausen1012** [comment]
If that's the case, I may not be able to use transfer.zip on the local area network, but thank you for your work and response. If possible, I would prefer transfer.zip to have a branch that supports HTTP
