### ISSUE TITLE
The signaling server doesn't start.

### ISSUE THREAD

**Issue by LazyDevv** [robinkarlberg/transfer.zip-web#24]
Building in docker just gets docker stuck at 23/29 and trying to run it manually just gets it stuck again.
![image](https://github.com/user-attachments/assets/59d82915-4cf8-4594-bc8c-eef41a022c85)
Visiting localhost:8001 just says "Upgrade Required"

**Comment by robinkarlberg** [comment]
Hi, could you provide some more information on what stage your docker build gets stuck on, like build logs, or a screenshot of the build output.

Also, when you run it manually it does not actually get stuck, I have just not made it print "running" or something. It saying "Upgrade Required" on localhost:8001 means the websocket server is indeed running, but only accepts websocket connections, not visiting it like a website. So running it manually should work for you, in combination with the web server.

**Comment by LazyDevv** [comment]
Hey! Thanks for the quick response.

Seems the issue was me configuring the .env file wrong as I thought I had to put the signaling server in there, turns out just leaving it blank works haha.

Definitely a user error on my parts. Thanks for the response once again.
