### ISSUE TITLE
Provide container images on DockerHub

### ISSUE THREAD

**Issue by l4rm4nd** [robinkarlberg/transfer.zip-web#4]
Nice project, thanks.

Would it be possible that you build the images (e.g. via GitHub Actions) and provide them via Dockerhub? Would be easier for people to try out the project without self-building.

Cheers.

**Comment by robinkarlberg** [comment]
Hi, thanks for the kind words! 

Unfortunately, publishing transfer.zip as a docker image is not a priority at the moment.
