### ISSUE TITLE
Links time out REALLY fast and don't tell the sender when they time out

### ISSUE THREAD

**Issue by ArrayBolt3** [robinkarlberg/transfer.zip-web#8]
If I choose to send a file, then share the transfer link with someone else, it just says "Waiting for peer..." on my end. If the user on the other end doesn't immediately click the link, they get a "recipient does not exist" error message. I never see anything about the link having expired however. The links also seem to expire very quickly - after just two minutes it already doesn't allow the receiver to download the file.

If possible, it would be nice if the time before the link expires was lengthened to five minutes or so (assuming that doesn't put undue load on your server keeping track of people who are trying to transfer things), and it would be nice if the sender got some message indicating that the link had expired if no one downloaded the file being sent within the time limit.

**Comment by robinkarlberg** [comment]
Closing because of no response

**Comment by ArrayBolt3** [comment]
Gah, I thought I forgot something... :P Sorry about that, I'll try to reproduce it again and provide more complete info later.

**Comment by robinkarlberg** [comment]
Hi! No worries, I'll reopen the issue if you are able to reproduce it again! :)
