### ISSUE TITLE
Folder instead of just File?

### ISSUE THREAD

**Issue by buthig666** [robinkarlberg/transfer.zip-web#9]
I would love to have the same functionality with folders.  Sometimes there are many files in a project and that is cumbersome and confusing.  

Any chance we could send a folder instead of just a file?

**Comment by buthig666** [comment]
please?

**Comment by mathiasmagnusson** [comment]
Unfortunately there is no standard way to either upload or download a folder in a web browser.

Uploading a directory is pretty well supported with [webkitdirectory](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory), but not standard, and as far as I know, there is no support for downloading a folder.

I think the easiest solution is to create either a tar or zip archive and transfer it using this website.

**Comment by buthig666** [comment]
ok thanks
